#!/bin/bash

# workaround for "missing group puppet" bug
groupadd -g 499 puppet

# Firewall configuration for foreman
#systemctl stop  firewalld.service
#systemctl disable firewalld.service
#firewall-cmd --permanent --zone=public --add-interface=enp0s8
#firewall-cmd --permanent --add-port=53/tcp
#firewall-cmd --permanent --add-port=67-69/udp
#firewall-cmd --permanent --add-port=80/tcp
#firewall-cmd --permanent --add-port=443/tcp
#firewall-cmd --permanent --add-port=5910-5930/tcp
#firewall-cmd --permanent --add-port=5432/tcp
#firewall-cmd --permanent --add-port=8140/tcp
#firewall-cmd --permanent --add-port=8443/tcp
#firewall-cmd --reload

# place answer file...
cp /vagrant/foreman-answers.yaml /etc/foreman-installer/scenarios.d/foreman-answers.yaml
# ... and run foreman-installer
#foreman-installer

