#!/bin/bash

foreman-installer \
  --enable-foreman-proxy \
  --foreman-proxy-tftp=true \
  --foreman-proxy-tftp-servername=10.1.128.26 \
  --foreman-proxy-dhcp=true \
  --foreman-proxy-dhcp-interface=enp0s8 \
  --foreman-proxy-dhcp-gateway=10.0.2.15 \
  --foreman-proxy-dhcp-nameservers="10.1.128.26" \
  --foreman-proxy-dns=true \
  --foreman-proxy-dns-interface=enp0s8 \
  --foreman-proxy-dns-zone=ubelix.unibe.ch \
  --foreman-proxy-dns-reverse=1.10.in-addr.arpa \
  --foreman-proxy-dns-forwarders=10.0.2.3 \
  --foreman-proxy-foreman-base-url=https://foreman02.ubelix.unibe.ch \
  --foreman-proxy-oauth-consumer-key=H3qpo6nzr2fub3thbnCYg8AdXobxGv9p \
  --foreman-proxy-oauth-consumer-secret=uD3wRj9yMdZFt8Z4UvF5bybfPFmWjfpH
