#!/bin/bash

elmajver="7"
pupcolrel_version="pc1"

pupcolrel_url="http://yum.puppetlabs.com/puppetlabs-release-${pupcolrel_version}-el-${elmajver}.noarch.rpm"

if ! rpm -qa | grep puppetlabs-release-$pupcolrel_version >/dev/null 2>&1; then
  sudo yum -y install bash-completion epel $pupcolrel_url
  sudo yum clean all
  sudo yum makecache
else
  echo "Puppet Collection is available."
fi

if [ ! -f /etc/profile.d/puppet-agent.sh ]; then
  yum -y install puppet-agent
  source /etc/profile.d/puppet-agent.sh
else
  echo "Puppet agent is installed."
fi

echo "Now add dns_alt_names if necessary (puppetdb/foreman)"
echo "and run puppet agent."
#puppet agent -t --waitforcert 30

exit 0

