#!/bin/bash

elmajver="7"
pupcolrel_version="pc1"

pupcolrel_url="http://yum.puppetlabs.com/puppetlabs-release-${pupcolrel_version}-el-${elmajver}.noarch.rpm"

if ! rpm -qa | grep puppetlabs-release-$pupcolrel_version >/dev/null 2>&1; then
  sudo yum -y install $pupcolrel_url
  sudo yum clean all
  sudo yum makecache
else
  echo "Puppet Collection is available."
fi

