#!/usr/bin/env bash

BIN_DIR=$(dirname -- $(readlink -f $0))

# Git is needed for r10k to work.
if ! type git >/dev/null 2>&1; then
  yum -y install git >/dev/null
fi

# Install r10k gem in appropriate location and
# generate necessary directories.
if ! type r10k >/dev/null 2>&1; then
  /opt/puppetlabs/puppet/bin/gem install r10k
  ln -s /opt/puppetlabs/puppet/bin/r10k /opt/puppetlabs/bin/r10k
  mkdir -p /etc/puppetlabs/r10k
  mkdir -p /opt/puppetlabs/r10k/cache
fi

# Configuration of r10k
cat << EOF >> /etc/puppetlabs/r10k/r10k.yaml
# The location to use for storing cached Git repos
:cachedir: '/opt/puppetlabs/r10k/cache'

# A list of git repositories to create
:sources:
  # This will clone the git repository and instantiate an environment per
  # branch in /etc/puppetlabs/code/environments
  :ubelix-puppetenv:
    remote: 'ssh://git@idos-code.unibe.ch:7999/ubelix/puppetenv.git'
    basedir: '/etc/puppetlabs/code/environments'
    prefix: false
EOF

# Add public read only key for UBELIX to do stash clones
if [ ! -d ~/.ssh/ ]; then
  mkdir -p ~/.ssh/
  chmod 700 ~/.ssh/
fi

if [ ! -f ~/.ssh/ubelix_stash_rsa ]; then
  cp $BIN_DIR/resources/ubelix_stash_rsa ~/.ssh/
  cp $BIN_DIR/resources/ubelix_stash_rsa.pub ~/.ssh/
  chmod 600 ~/.ssh/ubelix_stash_rsa
fi

if ! cat ~/.ssh/config 2>/dev/null | grep "idos-code" >/dev/null; then
  cat << 'EOF' >> ~/.ssh/config


Host idos-code.unibe.ch
    User git
    Hostname idos-code.unibe.ch
    PreferredAuthentications publickey
    IdentityFile ~/.ssh/ubelix_stash_rsa

EOF
fi

if [ ! -f ~/.ssh/known_hosts ] || ! cat ~/.ssh/known_hosts 2>/devnull | grep "idos-code" >/dev/null; then
  cat << 'EOF' >> ~/.ssh/known_hosts
[idos-code.unibe.ch]:7999,[130.92.253.206]:7999 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCrC7tqEA/QDGCito53+9nO/n8ndXYqrNvqWfoOZS87heChNsYykbWIOqMdYisV+ELgniDQb0BFXAieHq+Rs3Y1PduoYbRXIjoqpVf8hxbrKdcbYNh+xizWuaeZ3UAK1rFaESnPOWn+cVK4HIFPc9oREj4rhSAFDVAF7DLA0S3tPLhhUuVcTkXYENyGY1AvFfEp5aCyA2d0WuRci1Mt5w8PuH40mP5sCXH8IZ6dIydypNMtQHdNbKMcit4dKrgAWlqHvg+eW4AMiidyEDz9z25mivcQPBNbnK2/IfW1IeavafhLHF2mTQkzvzm7leJ7v8J9aJtt2aGqM+JYokucW+XL
EOF
fi

echo "R10K is now setup"
echo "Now deploy the environemnts and test it i.e. with hiera:"
echo "  r10k deploy environment -pv"
echo "  hiera -d ntp::servers environment=development ::role=infraserver ::subrole=service"

